Click did not pull in click-plugins, so it would fail unless I added it manually.
 [...] File "/Users/jj/src/git/safespring/python-jerakia/jerakia/cli.py", line 11, in <module>
    from click_plugins import with_plugins
ImportError: No module named click_plugins

...
pip install click_plugins
..
jerakia lookup --help

Usage: jerakia lookup [OPTIONS] NAMESPACE KEY